baseURL = "https://bomhort.dev/"
languageCode = "en-us"
title = "BOMHort"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Open source, Kubernetes-native SBOM management & software supply chain security: ingest SPDX/CycloneDX SBOMs, scan vulnerabilities, enforce licenses, CRA readiness."
  keywords = "SBOM management, Software Bill of Materials, Cyber Resilience Act, CRA compliance, vulnerability check, vulnerability scanning, OSV, CycloneDX, SPDX, VEX, OpenVEX, software supply chain security, license compliance, dependency management, Kubernetes security, SBOM analytics, open source security, OpenSSF, CVE tracking"
  githubRepo = "https://github.com/seebom-labs/BOMHort"
  author = "BOMHort Community"
  ogImage = "/images/bomhort-mascot-favicon.png"
  twitter = ""

[menu]
  [[menu.main]]
    name = "Documentation"
    url = "https://docs.bomhort.dev"
    weight = 10
    [menu.main.params]
      icon = "book-open"
  [[menu.main]]
    name = "Community"
    pageRef = "/community"
    weight = 20
    [menu.main.params]
      icon = "users-group"
  [[menu.main]]
    name = "Blog"
    pageRef = "/blog"
    weight = 30
    [menu.main.params]
      icon = "newspaper"
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/seebom-labs/BOMHort"
    weight = 40
    [menu.main.params]
      icon = "github"








